### ISSUE TITLE
A Suggest!

### ISSUE THREAD

**Issue by freezy7** [CainLuo/CLUIKit#2]
兄弟，最近发现我和你有一个同样的以 CLUIKit和CLMapKit命名的库，我这边是以私有库的方式创建的，由于版本号的原因，引用到了你的高版本。顺便看了下你的`CLUIKit`和`CLMapKit`,提几点建议哈：

- CLUIKit功能有点太过于丰富了，扩展的话我认为最好是方便易用，简洁。
- 控件的话完全可以抽离出来，不必放入CLUIKit。
- README我觉得还是要简单点，详细介绍还是需要一个API的文档最好。
- 版本升级有点过于快了，如果希望大家使用，Release Note是不是也需要完善下。

总之，为了解决冲突的问题，之前我只是做了升高我自己的版本号，现在我只能指定Source了。

我个人理解，就说对UIKit和Foundation的扩展吧，OC有`YYKit`, swift有`SwifterSwift`,这些库很好的解决了大家的公共需求。对VC层扩展的话，跟业务逻辑就比较耦合了，需要根据不同的业务逻辑做不同的页面架构，当然不能保证所有的VC架构都是一样的。所以页面逻辑的架构我这边就抽象出供自己业务使用的架构了，但是碰巧的是我们使用了同样的名字🙂。

Good Luck! 🤝

**Comment by CainLuo** [comment]
居然这么巧合? 我这个库的名字是以我的英文名首字母命名的, 没想到这样子也会有重复~, 哈哈, 这里我回答几点哈~~

- CLUIKit大部分是对类库的一个扩展, 真正封装起来的也不多, 现在对于我的业务需求来说, 目前是满足的, 后续也会慢慢的优化
- README的话, 目前实在没时间抽空去写了, 等后面闲下来再慢慢整理吧
- 版本升级太快, 这个有些尴尬, 本身我是想把CLMapKit集成进去的, 但是发现CocoaPods貌似不能选择性的导入工程, 而目前的业务也并不是所有项目都要用到地图, 头痛的是已经发布了的CocoaPods貌似不能删除, 这个也是很无奈.

对于给您造成了麻烦, 实在不好意思, 或者您可以改改你的版本号格式, 往更高的版本号设置?

谢谢您的建议, 虽然`YYKit`与`SwifterSwift`都不错, 但我们所熟悉的还是自己写的那套不是吗?

**Comment by freezy7** [comment]
会错误的引用到你的库的问题我这边已经解决了，`CocoaPods`是可以作废库，不过根据你具体因应用场景吧看你具体怎么处理好了。

在业务逻辑这一层做封装，依赖是很多的，而且梳理好这些依赖也是很麻烦的，所以要保证尽量的简而精。建议你进行再次拆分，或者底层用一些公用库对架构进一步优化解耦隔离。

对于选择性导入工程，给你支个招，头文件引用依赖的话尝试下这个宏进行预编译:

```objc
#if (__has_include(<xxx/xxx.h>)
```

这样的话你的`podfile`如果不引用CLMapKit,代码就不会运行，就可以顺利编译使用了。

**Comment by CainLuo** [comment]
`CocoaPods`怎么作废库的? 可否支招? `CLMapKit`这个库基本上已经废了, 因为同时导入高德的2D和3D会冲突.

其实我并没有对业务逻辑这一层做封装, 目前所提供的都是一些基类库哦

您提供的头文件引用依赖的确不错, 但不太适合我, 我是想在`podspec`文件里可选择性的选择对应的库依赖并加载.

**Comment by freezy7** [comment]
[pod_trunk_deprecate](https://guides.cocoapods.org/terminal/commands.html#pod_trunk_deprecate)
[pod_trunk_delete](https://guides.cocoapods.org/terminal/commands.html#pod_trunk_delete)

**Comment by CainLuo** [comment]
谢谢大佬的指导~
